name: flutter_basic_library
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  pull_to_refresh: ^2.0.0
  fluro: ^2.0.3
  flutter_swiper_plus: ^2.0.4
  fl_chart: ^0.55.0
  flutter_pickers: ^2.1.9
  date_format: ^2.0.6
  flutter_easyloading: ^3.0.3
  event_bus: ^2.0.0
  # https://github.com/a14n/dart-decimal
  rational: ^2.2.0
  # https://github.com/a14n/dart-decimal
  decimal: ^2.2.0
  provider: ^6.0.3
  #链式
  velocity_x: 3.3.0
  source_gen: ^1.2.2
  path_provider: ^2.0.11
  flutter_svg: ^1.0.3
  sqflite: ^2.0.1
  shared_preferences: ^2.0.15
  rxdart: ^0.27.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.flutter_basic_library
        pluginClass: FlutterBasicLibraryPlugin
      ios:
        pluginClass: FlutterBasicLibraryPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
